version: '3.4'
services: 
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=192.168.0.104
      - PMA_USER:aveti
      - PMA_PASSWORD:'mypassword'
      - MYSQL_TCP_PORT:3306
    restart: always  
